import fs from 'node:fs';
const read = (file) => fs.readFileSync(file, 'utf8');
const write = (file, value) => fs.writeFileSync(file, value.replace(/\r\n/g, '\n'), 'utf8');
function literal(file, before, after, label) {
  let text = read(file);
  if (text.includes(after)) return;
  if (!text.includes(before)) throw new Error(`${file}: missing ${label}`);
  write(file, text.replace(before, after));
}
function regex(file, pattern, after, label) {
  let text = read(file);
  if (text.includes(after)) return;
  if (!pattern.test(text)) throw new Error(`${file}: missing ${label}`);
  write(file, text.replace(pattern, after));
}
literal('public/index.html', "<div><small>ELECTRONIC FLIGHT BAG</small><h1 data-i18n=\"welcome\">Good evening, Captain</h1><p data-i18n=\"selectApp\">Select an application to continue.</p></div>\n            <div class=\"home-heading-actions\"><button id=\"home-new-flight\" class=\"secondary-card-action\" type=\"button\" data-i18n=\"newFlight\">NEW FLIGHT</button><div class=\"home-time\"><strong id=\"home-clock\">—</strong><span>LOCAL TIME</span></div></div>", "<div><small>ELECTRONIC FLIGHT BAG</small><h1 id=\"home-greeting\">Guten Abend, Captain</h1><p data-i18n=\"selectApp\">Select an application to continue.</p></div>\n            <div class=\"home-heading-actions\"><button id=\"home-simbrief-import\" class=\"secondary-card-action\" type=\"button\">SIMBRIEF OFP</button><button id=\"home-new-flight\" class=\"secondary-card-action\" type=\"button\" data-i18n=\"newFlight\">NEW FLIGHT</button><div class=\"home-time\"><strong id=\"home-clock\">—</strong><span>LOCAL TIME</span></div></div>", 'home greeting/actions');
literal('public/index.html', "<span class=\"app-tile-copy\"><small>FLIGHT OPS</small><strong data-i18n=\"flight\">Flight</strong><span data-i18n=\"flightSummary\">SimBrief plan and live MSFS data</span></span><i class=\"app-open-arrow\">›</i>", "<span class=\"app-tile-copy\"><small>FLIGHT OPS &amp; TRACKING</small><strong>Flug &amp; Tracking</strong><span>Flugplanung, Live-Daten, Karte, Flugspur und Archiv</span></span><i class=\"app-open-arrow\">›</i>", 'flight hub tile');
{
  let text = read('public/index.html');
  text = text.replace(/\n\s*<button class="efb-app-tile tracking-app"[\s\S]*?<\/button>/, '');
  write('public/index.html', text);
}
literal('public/index.html', "<header class=\"page-heading\"><div><small>FLIGHT OPERATIONS</small><h1 data-i18n=\"flight\">Flight</h1><p data-i18n=\"flightPageIntro\">Import the latest SimBrief OFP and compare it with live simulator data.</p></div><span id=\"flight-status-pill\" class=\"module-status waiting\">NO OFP</span></header>", "<header class=\"page-heading\"><div><small>FLIGHT OPERATIONS</small><h1 data-i18n=\"flight\">Flight</h1><p data-i18n=\"flightPageIntro\">Import the latest SimBrief OFP and compare it with live simulator data.</p></div><span id=\"flight-status-pill\" class=\"module-status waiting\">NO OFP</span></header>\n          <nav class=\"floating-section-nav flight-hub-nav\" aria-label=\"Flight Hub\"><button type=\"button\" class=\"active\" data-flight-hub-view=\"flight\">OPERATIONS</button><button type=\"button\" data-flight-hub-view=\"tracking\">TRACKING &amp; KARTE</button><button type=\"button\" data-flight-hub-view=\"tracking\" data-tracking-section=\"archive\">ARCHIV</button></nav>", 'flight hub nav');
literal('public/index.html', "<header class=\"page-heading tracking-heading\"><div><small>LIVE FLIGHT OPERATIONS</small><h1 data-i18n=\"tracking\">Flight Tracking</h1><p data-i18n=\"trackingIntro\">Follow the current flight and reopen every recorded flight with route, weather and simulator data.</p></div><span id=\"tracking-status-pill\" class=\"module-status waiting\">WAITING</span></header>", "<header class=\"page-heading tracking-heading\"><div><small>LIVE FLIGHT OPERATIONS</small><h1 data-i18n=\"tracking\">Flight Tracking</h1><p data-i18n=\"trackingIntro\">Follow the current flight and reopen every recorded flight with route, weather and simulator data.</p></div><span id=\"tracking-status-pill\" class=\"module-status waiting\">WAITING</span></header>\n          <nav class=\"floating-section-nav flight-hub-nav\" aria-label=\"Flight Hub\"><button type=\"button\" data-flight-hub-view=\"flight\">OPERATIONS</button><button type=\"button\" class=\"active\" data-flight-hub-view=\"tracking\">TRACKING &amp; KARTE</button><button type=\"button\" data-flight-hub-view=\"tracking\" data-tracking-section=\"archive\">ARCHIV</button></nav>", 'tracking hub nav');
literal('public/index.html', "<div class=\"tracking-recorder-actions\"><button id=\"tracking-start\" class=\"primary-card-action\" type=\"button\" data-i18n=\"startRecording\">START RECORDING</button><button id=\"tracking-save\" class=\"secondary-card-action\" type=\"button\" data-i18n=\"saveFlight\">SAVE FLIGHT</button><button id=\"tracking-live\" class=\"secondary-card-action\" type=\"button\" hidden data-i18n=\"backLive\">BACK TO LIVE</button></div>", "<div class=\"tracking-recorder-actions\"><span class=\"automatic-recorder-badge\">● AUTOMATISCH</span><button id=\"tracking-save\" class=\"secondary-card-action\" type=\"button\" data-i18n=\"saveFlight\">FLUG ABSCHLIESSEN</button><button id=\"tracking-live\" class=\"secondary-card-action\" type=\"button\" hidden data-i18n=\"backLive\">ZURÜCK ZU LIVE</button></div>", 'automatic recorder controls');
literal('public/index.html', "<div class=\"tracking-legend\"><span><i class=\"planned\"></i><b data-i18n=\"plannedRoute\">Planned route</b></span><span><i class=\"actual\"></i><b data-i18n=\"actualTrack\">Actual track</b></span><span><i class=\"waypoint\"></i><b data-i18n=\"allWaypoints\">All waypoints</b></span></div>", "<div class=\"tracking-legend\"><span><i class=\"planned\"></i><b data-i18n=\"plannedRoute\">Planned route</b></span><span><i class=\"actual\"></i><b data-i18n=\"actualTrack\">Actual track</b></span><span><i class=\"waypoint\"></i><b data-i18n=\"allWaypoints\">All waypoints</b></span><span><i class=\"traffic\"></i><b>Traffic / beobachtete Route</b></span></div>", 'tracking traffic legend');
literal('public/index.html', "<article class=\"efb-card com-presets-card\"><div class=\"section-title\"><div><small>ATC / AIRPORT</small><h2 data-i18n=\"availableFrequencies\">Available frequencies</h2></div><span>CLICK TO STANDBY</span></div>", "<article id=\"com-next-station-card\" class=\"efb-card com-next-station-card\"><div class=\"section-title\"><div><small>NÄCHSTE SINNVOLLE STATION</small><h2 id=\"com-next-station\">Wird ermittelt …</h2></div><strong id=\"com-next-frequency\">—</strong></div><p id=\"com-next-reason\" class=\"help-text\">Die Empfehlung berücksichtigt Flugphase, Airport und aktuell verfügbare ATC-Frequenzen. Es wird niemals automatisch getuned.</p><button id=\"com-next-tune\" class=\"primary-card-action\" type=\"button\" disabled>AUF COM1 STANDBY</button></article>\n            <article class=\"efb-card com-presets-card\"><div class=\"section-title\"><div><small>ATC / AIRPORT</small><h2 data-i18n=\"availableFrequencies\">Available frequencies</h2></div><span>CLICK TO STANDBY</span></div>", 'COM next station card');
literal('public/index.html', "<header class=\"page-heading\"><div><small>ATC &amp; LIVE NETWORKS</small><h1 data-i18n=\"atcCenter\">ATC Center</h1><p data-i18n=\"atcCombinedIntro\">Clearances, all SayIntentions messages and read-only online network data in one place.</p></div><span id=\"atc-active-pill\" class=\"module-status waiting\">AUTO</span></header>", "<header class=\"page-heading\"><div><small>ATC &amp; LIVE NETWORKS</small><h1 data-i18n=\"atcCenter\">ATC Center</h1><p data-i18n=\"atcCombinedIntro\">Clearances, all SayIntentions messages and read-only online network data in one place.</p></div><span id=\"atc-active-pill\" class=\"module-status waiting\">AUTO</span></header>\n          <nav class=\"floating-section-nav atc-subnav\" aria-label=\"ATC Bereiche\"><button type=\"button\" data-scroll-target=\"atc-provider-section\">QUELLE</button><button type=\"button\" data-scroll-target=\"atc-clearance-section\">FREIGABE</button><button type=\"button\" data-scroll-target=\"atc-messages-section\">NACHRICHTEN</button><button type=\"button\" data-scroll-target=\"atc-networks-section\">VATSIM / IVAO</button></nav>", 'ATC floating nav');
literal('public/index.html', "<article class=\"efb-card provider-panel\">", "<article id=\"atc-provider-section\" class=\"efb-card provider-panel\">", "atc provider id");
literal('public/index.html', "<article class=\"efb-card clearance-panel\">", "<article id=\"atc-clearance-section\" class=\"efb-card clearance-panel\">", "atc clearance id");
literal('public/index.html', "<article class=\"efb-card atc-messages-card\">", "<article id=\"atc-messages-section\" class=\"efb-card atc-messages-card\">", "atc messages id");
literal('public/index.html', "<article class=\"efb-card network-selector-card\">", "<article id=\"atc-networks-section\" class=\"efb-card network-selector-card\">", "atc networks id");

console.log('Applied 1.4.0 Home/Flight/COM/ATC HTML changes.');
